### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by louis-6wind** [SmartValidator/rtr-python#2]
Hello,

thank you for publishing your RPKI server daemon.

We are interested in using it in the CI of the FRR project. See https://github.com/FRRouting/frr/pull/15034

However, our project is GPL-2 and yours is GPL-3. Would you mind changing the license to GPL-2?

**Comment by tmshlvck** [comment]
In principle yes. This piece of code has been created as a quick prototype for testing and since the whole thing kind-of died, it would be great if you could pick it up and use+maintain it as a part of your CI. However this whole project has a history of licensing issues and later disputes between individuals working on it and the institutes funding it. Even though I would consider it to be abandonware, I guess the best option would be to take this Python script and simply re-implement it, using a bit more modern approach.

If you really want, I guess I could do it for you and release the result under GPL2.

**Comment by louis-6wind** [comment]
> If you really want, I guess I could do it for you and release the result under GPL2.

It would be great. FRR maintainers require it : https://github.com/FRRouting/frr/pull/15034#issuecomment-1863996287

**Comment by tmshlvck** [comment]
FYI: Here is the re-implementation that is licenced under GPL 2.0: https://github.com/tmshlvck/pyrtr
